import { encodeKeys, orderColMajor, encode } from './positions.js';

const q = (v) =>
  v === undefined || v === null || v === ''
    ? 'null'
    : `'${String(v).replace(/'/g, "''")}'`;

function cellsByRole(region, role) {
  return Object.entries(region.cells)
    .filter(([, r]) => r === role)
    .map(([k]) => k);
}

export function generateSql(data) {
  const { rows, cols, encoding, header, regions } = data;
  const h = header;
  const schema = h.schema || 'ISR_DAT';
  const hdrTable = `${schema}.${h.hdrTable}`;
  const dtlTable = `${schema}.${h.dtlTable}`;
  const fmt = h.formatName;

  const hdrCols =
    'TILE_FORMAT_ID,FORMAT_NAME,APP_VER_START,CHAIN_ID,APP_VER_END,IS_ACTIVE,' +
    'ROW_COUNT,COLUMN_COUNT,TOTAL_POSITIONS,CREATION_TIME,CREATED_BY,LAST_UPDATED_DATE,' +
    'LAST_UPDATED_BY,TILE_HEIGHT,ATTR_VALUE_TYPE,ATTR_MATH,DEVICE_CONFIG_NAME';

  const hdr =
    `Insert into ${hdrTable} (${hdrCols}) values (` +
    `${schema}.${h.hdrSeq}.NEXTVAL,${q(fmt)},${q(h.appVer)},${q(h.chain)},null,'Y',` +
    `${rows},${cols},${rows * cols},SYSDATE,${q(h.createdBy)},SYSDATE,${q(h.createdBy)},` +
    `${q(h.tileHeight)},null,null,${q(h.deviceConfig)});`;

  const sub = `(SELECT TILE_FORMAT_ID from ${hdrTable} WHERE FORMAT_NAME=${q(fmt)})`;

  const dtlCols =
    'TILE_FORMAT_DTL_ID,TILE_FORMAT_ID,POSITION_IDS,ATTR_NAME,ATTR_VALUE,NAME_CSS,' +
    'VALUE_CSS,NAME_POS_ID,VALUE_POS_ID,SOURCE,CREATION_TIME,CREATED_BY,LAST_UPDATED_DATE,' +
    'LAST_UPDATED_BY,ATTR_VALUE_TYPE,ATTR_MATH';

  const dtl = regions.map((rg) => {
    const nameCells = cellsByRole(rg, 'name');
    const valCells = cellsByRole(rg, 'value');
    const allCells = Object.keys(rg.cells);
    const POS = encodeKeys(encoding, allCells, cols);
    const NPOS = nameCells.length ? encodeKeys(encoding, nameCells, cols) : null;
    const VPOS = valCells.length ? encodeKeys(encoding, valCells, cols) : null;
    const hasName = !!rg.name;
    const comment = `-- ${rg.name ? rg.name + ' -> ' : ''}${rg.value || '(unset)'}`;
    const line =
      `Insert into ${dtlTable} (${dtlCols}) values (` +
      `${schema}.${h.dtlSeq}.NEXTVAL,${sub},${q(POS)},${q(rg.name)},${q(rg.value)},` +
      `${hasName ? q(rg.nameCss) : 'null'},${q(rg.valueCss)},${q(NPOS)},${q(VPOS)},` +
      `${q(rg.source)},SYSDATE,${q(h.createdBy)},SYSDATE,${q(h.createdBy)},` +
      `${q(rg.valueType)},${q(rg.math)});`;
    return `${comment}\n${line}`;
  });

  const banner = [
    '--------------------------------------------------------------------------------',
    `-- ${fmt}  (${rows} x ${cols}, ${rows * cols} positions)`,
    `-- Position encoding: ${encoding}`,
    '-- Generated by Order Tile Designer',
    '--------------------------------------------------------------------------------',
  ].join('\n');

  return `${banner}\n\n${hdr}\n\n${dtl.join('\n\n')}\n\nCOMMIT;\n`;
}

// Sample positions string for the currently selected encoding (UI helper).
export function samplePositions(encoding, cols) {
  const a = encode(encoding, 1, 1, cols);
  const b = encode(encoding, 2, 3, cols);
  const z = encode(encoding, 11, 12, cols);
  return `${a}, ${b}, … ${z}`;
}

export { orderColMajor };
